services:
  - type: web
    name: aethercrown-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/health"
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: PAYPAL_SECRET
        value: ${PAYPAL_SECRET}
      - key: API_URL
        value: ${API_URL}
  - type: cron
    name: aethercrown-automation
    env: python
    schedule: "0 */6 * * *" # every 6 hours
    command: "python backend/empire_automation.py"
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: PAYPAL_SECRET
        value: ${PAYPAL_SECRET}