version: "1"
services:
- type: web
  name: AetherCrown20-backend
  env: python
  repo: https://github.com/monkeymadness98/AetherCrown20
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT --workers 2 --log-level info
  autoDeploy: true
  envVars:
  - key: PAYPAL_CLIENT_ID
    sync: false
  - key: PAYPAL_SECRET
    sync: false
  - key: ENV
    value: production
    sync: false