services:
  - type: web
    name: backend
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT --workers 2 --log-level info
    envVars:
      - key: ENV
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_SECRET
        sync: false