name: Scheduled Sweep

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  sweep:
    name: Run AI Agent Sweep
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-sweep-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-sweep-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install httpx pytest pytest-asyncio
      
      - name: Run sweep
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_SECRET: ${{ secrets.PAYPAL_SECRET }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: |
          python backend/sweep_cli.py --output sweep_report_$(date +%Y%m%d_%H%M%S).md
      
      - name: Upload sweep report
        uses: actions/upload-artifact@v3
        with:
          name: sweep-report-${{ github.run_number }}
          path: sweep_report_*.md
          retention-days: 30
      
      - name: Check for critical errors
        run: |
          if grep -q "Total Errors: 0" sweep_report_*.md; then
            echo "✅ Sweep completed with no errors"
            exit 0
          else
            echo "⚠️ Sweep found errors - check the report"
            # Don't fail the workflow, just warn
            exit 0
          fi
      
      - name: Comment on monitoring issue (optional)
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const reportFiles = fs.readdirSync('.').filter(f => f.startsWith('sweep_report_'));
            if (reportFiles.length > 0) {
              const reportContent = fs.readFileSync(reportFiles[0], 'utf8');
              const lines = reportContent.split('\n').slice(0, 50); // First 50 lines
              const summary = lines.join('\n');
              
              console.log('Sweep report generated:');
              console.log(summary);
              
              // Optionally post to an issue or PR
              // github.rest.issues.createComment({
              //   issue_number: MONITORING_ISSUE_NUMBER,
              //   owner: context.repo.owner,
              //   repo: context.repo.repo,
              //   body: `## Sweep Report\n\n${summary}\n\n[View full report in artifacts](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
              // });
            }
        continue-on-error: true
